<a href="https://colab.research.google.com/github/juancasi/data_science_fundamentals/blob/master/chapter_04/numpy_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [4]:
import numpy as np 
arr = np.array([7,8,4,5,1,2])
print(arr)

[7 8 4 5 1 2]


Using slicing print the elements from index 3 to the end of the array.



In [2]:
print(arr[3:])

[5 1 2]


Using slicing print all the elements except the last one.



In [3]:
print(arr[:-1])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [4]:
print(arr[1:4])

[8 4 5]


Reshape the array into a 3 rows and 2 cols (3,2).



In [5]:
newarr = arr.reshape(3, 2)
print(newarr)

[[7 8]
 [4 5]
 [1 2]]


Print all the array elements one by one (iterating).



In [2]:
for x in arr:
    print(x)

7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [2]:
arr1 = np.array([0, 6, 9])
print(arr1)

[0 6 9]


Join the two arrays.



In [3]:
arr2 = np.concatenate((arr, arr1))
print(arr2)

[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [5]:
filtro = []
for element in arr2:
    if element % 2 != 0:
        filtro.append(True)
    else:
     filtro.append(False)

arr_fil = arr2[filtro]

print(arr_fil)


[7 5 1 9]


Sort the joined array elements.



In [6]:
print(np.sort(arr2))

[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [3]:
meses = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])
print(meses)

['Enero' 'Febrero' 'Marzo' 'Abril' 'Mayo' 'Junio' 'Julio' 'Agosto'
 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']


Split the months array in 4 periods of 3 elements each one.



In [4]:
meses1 = np.array_split(meses, 4)
print(meses1[0])
print(meses1[1])
print(meses1[2])
print(meses1[3])

['Enero' 'Febrero' 'Marzo']
['Abril' 'Mayo' 'Junio']
['Julio' 'Agosto' 'Septiembre']
['Octubre' 'Noviembre' 'Diciembre']


Create an array with genre information ['F','M','F','F','M','F'].



In [5]:
gen = np.array (['F','M','F','F','M','F'])
print(gen)

['F' 'M' 'F' 'F' 'M' 'F']


Find the indexes where the value is F.



In [6]:
for i in range(len(gen)):
    f = gen[i]
    if f == 'F':
        print(i)
    else:
        pass

0
2
3
5


Store in an array the age information [18,20,19,23,19,20].



In [3]:
edad = np.array([18, 20, 19, 23, 19, 20])
print(edad)

[18 20 19 23 19 20]


Create a filter array with values < 20.



In [5]:
edad_f = []
for element in edad:
    if element < 20:
        edad_f.append(True)
    else:
        edad_f.append(False)
edad1 = edad[edad_f]
print(edad1)

[18 19 19]


Change the 3 index element with a value of 22



In [7]:
c = edad.copy()
edad[3] = 22
print(c)

[18 20 19 22 19 20]


Print the 4 index element.

In [8]:
print(edad[4])

19
